pixell/enmap.py

This PR allows the normalization flag in enmap.fft and enmap.map2harm to ask for a "physical" normalization such that the binned square of the fourier map can be directly compared to the power spectrum in physical units (i.e. steradians, not pixel units).

Physical normalization for FFT

---

setup.py

This is perhaps enough to close #43?  This addresses the issue in two ways:
- If the setup() call succeeds, a success message is printed, on the last line of output.  This is, like, the corollary of a Big Error Message.  It's not as easy to print a BEM, on failure, since setup() catches fails internally and then sys.exit(1).
- A distutils error is raised if the subprocess calls (make -C cython / fortran) fail.  This makes it easier to track down the actual error.

setup.py detects failure of custom build steps.

---

pixell/enmap.py
pixell/utils.py

This PR adds a routine enmap.cutsky_geometry that returns  a shape,wcs pair for a sky wrapped geometry that has a minimum and maxmimum declination. It also changes some `xrange` to `range` for Python 3 compatibility.

Cut-sky geometry and some python 3 updates

---

docs/conf.py
docs/reference.rst
docs/usage.rst
pixell/enmap.py

1. Add a section on creating enmaps; explain RA vs. Dec axes a little more.
2. Add basic documentation to enmap.py creating functions (empty,zeros,ones,full).
3. In the reference section, include all members (even undocumented ones) and list them in source order rather than alphabetical order.

More enmap docs

---

pixell/enmap.py
pixell/wcsutils.py
tests/test_geom.py

The main purpose of this PR is to properly set the reference point in Zenithal projections.  The code that handled "ref" was ok for cylindrical projections but does not generalize to, e.g., TAN.

Fix zenithal ref

---

docs/usage.rst
pixell/curvedsky.py
pixell/enmap.py
pixell/wcsutils.py
tests/test_pixell.py

This fixes #79 . It extends the functionality of the "plain" wcs type preventing it from throwing out its units, and it provides drop in replacements for some enmap functions for the simpler plain/Cartesian system.

Support for plain/Cartesian (true flat-sky) coordinate systems

---

pixell/enmap.py

to allow, e.g for a np.sum operation instead of np.mean when downgrading ivar maps.

Generalize enmap.downgrade

---

pixell/curvedsky.py
pixell/lensing.py

This PR adds two features:
1. Add a function to `pixell.curvedsky` to filter a map with SHTs
2. Add `lensing.rand_alm` called by `lensing.rand_map` so that the unlensed alms and phi alms can be reproduced

Curved sky helpers

---

pixell/curvedsky.py
pixell/tests/test_pixell.py

This PR fixes a bug in `curvedsky.prepare_alm` that causes the function to raise `AssertionError: lmax must be explicitly specified when lmax != mmax` when an alm array and an alm_info instance that both have mmax != lmax are provided (even when lmax is specified). I think this is a valid case, so with this change the function will allow lmax != mmax in cases where the user provides both an alm array and alm_info instance. I also added a test to `tests/test_pixell.py` to illustrate the desired behavior for different inputs.

Fixed bug for curvedsky.prepare_alm when lmax!=mmax alm and alm_info are provided

---

pixell/enmap.py

The bug would make it look like enmap.read_map was fliping stokes U even when it wasn't. It was caused by a misplaced parenthesis.

Fix misleading stokes print in verbose mode for enmap.read_map

---

pixell/bunch.py
pixell/curvedsky.py
pixell/enmap.py
pixell/enplot.py
pixell/utils.py

This is an import from my development repository. Mostly minor "nice-to-have" utilities. The most notable changes are probably bunch.write/read, which I think are quite handy; curvedsky.profile2harm/harm2profile, which makes it easy to transform e.g. a beam between its harmonic space and real-space representations, and utils.crossmatch, which provides quite fast and general crossmatching functionality.

Import from development branch: bunch I/O, 1d SHTs, np.interp wrapper, block reduce/expand, crossmatching, grouping

---

pixell/reproject.py
pixell/tests/test_pixell.py

I'll do spaces -> tabs throughout reproject.py in a separate PR or commit.

Thumbnails: pixel window deconvolution and unit tests

---

.github/workflows/build.yml
setup.py

Merging soon. This should fix the numpy binary incompatibility issue facing recent release versions. (Main change is requiring numpy > v1.20.0)

Fix issues with builds

---

cython/sharp.pyx
pixell/enmap.py

sharp.transfer_alm: Copy alm coefficients between alms
with diferent layouts, optionally accumulating.
enmap.resample_fft: The fourier-space portion of enmap.resample.
This turned out to be useful to have access to directly in fourier
space.
enmap.pixshapebounds: Provides the min and max vertical and
horizontal resolutions. Useful for reasoning about what lmax
a map needs, for example.
Also modified enmap.fullsky_geometry to handle cases with even numbers of pixels vertically. Previously this would place some pixel centers outside the sky. Now the start and end pixel vertically are always at the south and north pole, both for odd and even.

Added transfer_alm, resample_fft, pixshapebounds, bugfix in fullsky_geometry.

---

.github/workflows/build.yml

Ubuntu builds were failing because cibuildwheel >=2.2 now automatically tries to build for musl as well. Scipy didnt have precompiled wheels for musllinux, so it would try to build scipy, which requires lapack/blas, which ubuntu doesnt come with by default. To get around this, we skip musllinux builds, which we dont plan to support now.

Fix ubuntu build

---

pixell/enmap.py

Since Aug 10, 2021, enmap.downgrade has disregarded the "op" argument. This fixes this by passing "op" to block_reduce.

Bugfix for enmap.downgrade

---

pixell/wcsutils.py

The wcs pretty-print used to use %.4g format for crpix, but since crpix can often have 5 digits with our maps, that left off important information like the sub-pixel alignment. Changed it to have a fixed 0.01 pixel accuracy instead. This shouldn't make things too verbose.

Set wcs str to use 0.01 pixel accuracy for crpix instead of variable accuracy

---

pixell/curvedsky.py

Here's the surroundings previously
```python
def match_predefined_minfo(shape, wcs, rtol=None, atol=None):
"""Given an enmap with constant-latitude rows and constant longitude
intervals, return the libsharp predefined minfo with ringweights that's
the closest match to our pixelization. This function is actually
a bit slow, taking about 250 ms. Still subdominant to an SHT, though."""
if rtol is None: rtol = 1.0 # 1 pixel local error
if atol is None: atol = 1.0 # 1 pixel overall shift
flipy  = wcs.wcs.cdelt[1] > 0
if flipy: shape, wcs = enmap.slice_geometry(shape, wcs, [slice(None,None,-1)])
ntheta, nphi = shape[-2:]
theta  = np.pi/2 - enmap.pix2sky(shape, wcs, [np.arange(ntheta),np.zeros(ntheta)])[0]
phi0   = enmap.pix2sky(shape, wcs, [1,0])[1]
y1   = int(np.round(enmap.sky2pix(shape, wcs, …
```

remove redundant line in curvedsky

---

cython/srcsim_core.c
pixell/curvedsky.py
pixell/utils.py

Fix bug in curvedsky.match_predefined_mapinfo, that caused the integration weights to be missing in some cases with tweak=True. This would result in map2alm being very wrong. It was caused by a sharp predefined geometry that didn't actually have integration weights defined being included int he set of candidate closely-matching geometries.
Because I'm lazy, this pull also includes a WIP C-file that isn't used and that should be ignored for now.

Fix bug in curvedsky.match_predefined_mapinfo

---

pixell/enmap.py
pixell/multimap.py
scripts/build_wheels.sh

`clobber` argument when writing a `fits` file has been deprecated since few months now and has been
officially removed in version 5.1 of `astropy` (see https://github.com/astropy/astropy/blob/main/CHANGES.rst#astropyiofits-1)
This PR proposes to use the correct `overwrite` arguments but still makes the change backward compatible. This should also fix the github actions that are currently failing.

Change clobber argument to overwrite

---

cython/sharp_utils.c
setup.py

Here are two changes that allow for installation on Apple Silicon computers:
1. `setup.py` looks in `/usr/local/bin/` for `gcc` if it detects macOS. This is where homebrew installs things on Intel Macs, but on Silicon, homebrew instead puts things in `/opt/homebrew/bin/` (see https://docs.brew.sh/FAQ#why-should-i-install-homebrew-in-the-default-location). I've changed `setup.py` to look there if `gcc` is not found in `/usr/local/bin/`.
2. `cython/sharp_utils.c` includes `immintrin.h`, which includes x86 instructions that are not implemented on Silicon. The functions in `sharp_utils.c` that would use these are already turned off with preprocessor directives, so I've done the same for the `#include <immintrin.h>` line.

Fixes for running on Apple Silicon

---

setup.py

This little typo seems to prevent pip installation on python 3.11
Thanks to @zhuber21 for the report

Fix bad version code in setup.py

---

pixell/curvedsky.py
pixell/utils.py

When the input arrays were big-endian, ducc would either silently do the wrong thing or raise a RuntimeError. Avoid this by converting buffers to the native dtype. Bug reported by Ola.

Fix big endian problems with ducc

---

pixell/curvedsky.py
setup.cfg

Fix a bug where on rare occasions, fullsky maps would end up rotated in RA after an alm2map operation. This was caused by wcs.pix2world returning nan when evaluated at the map edge when bounds checking is turned on. Fixed by both turning off bounds checks and by using the middle of the map in declination instead of the bottom.

Fix alm2map 2d

---

pixell/enmap.py
pixell/enplot.py
pixell/tilemap.py
tests/test_pixell.py

Fixes warnings raised when running numpy 2.0 and the test suite. Removes around 12'000 errors from the test suite.

Fix numpy 2.0 errors

---

pixell/wavelets.py

This allows you to pre-filter maps sent into map2wave, which saves 2 SHTs.
It also allows you to specify wavelet coefficients that should be skipped, saving several alm2map operations if you don't need wavelet maps at all scales.

More flexibility in wavelets

---

.github/workflows/build.yml
Makefile
cython/cmisc.pyx
cython/cmisc_core.c
cython/distances_core.c
fortran/interpol.F90
meson.build
pixell/aberration.py
pixell/bunch.py
pixell/curvedsky.py
pixell/enmap.py
pixell/enplot.py
pixell/fft.py
pixell/pointsrcs.py
pixell/uharm.py
pixell/utils.py
pixell/wcsutils.py
pyproject.toml
tests/test_pixell.py

There is some chance of breakage with this update. It changes the mode keyword of utils.interpol and other functions that use it, such as enmap.at, enmap.project, etc. `mode` used to control the boundary conditions, but that's now called `border`. `mode` now controls the interpolation type, e.g. if it's spline-based. This was done to start adding non-uniform fft interpolation, which is partially implemented here, but still waiting for ducc to support incremental nuffts.
There is also a small change in the behavior of enmap.submap, which can cause 1-pixel shift in the size of the maps cut out with this operation due to differences in pixel rounding.
This update also contains the start of a new way to construct geometries that will make it easier to create patches with Fejer1 pixelization. …

Update from development repo

---

Makefile
pixell/cgrid.py
pixell/enmap.py
pixell/enplot.py
pixell/reproject.py
pixell/utils.py
pixell/wcsutils.py
tests/test_pixell.py

This pull request accumulates many minor changes, but changes some of the arguments to interpolation functions in order to support non-uniform fourier interpolation. This can break code that uses these arguments, but I'm not aware of any such code beyond my own.
Summary of the interpolation changes:
* Previously `utils.interpol`, and all functions built on top of it, like `enmap.at` and `enmap.project`, only supported ndimage.map_coordinate's spline interpolation. The `mode` argument controlled the boundary condition, while the `order` argument controlled the spline order. This has been changed such that `mode` now controls the interpolation type, while the boundary condition is controlled with the `border` argument.
* `mode` now has two valid values: "spline" for spline interpolation and …

Pull from development repo. Potentially breaking change in interpolation

---

pixell/enmap.py

Fixes https://github.com/simonsobs/pixell/issues/280

enmap.zeros replaced with zeros

---

pixell/wcsutils.py
tests/test_geom.py

geometry2() would always set lonpole=0 for zenithal projs, where geometry() would almost always set lonpole=180.  This PR:
- updates geometry() so it sets lonpole=180, even if CRVAL is the north pole.
- updates geometry2() to behave the same way as geometry().
- Adds ARC and SIN projections to geometry() (these were already supported by geometry2).
- Adds test to confirm that zenithal maps are oriented as we would like, by default, with the RA=0 line intersecting the bottom of the map.

Fix lonpole in zenithal projections

---

pixell/enmap.py
pixell/multimap.py
tests/test_pixell.py

This fixes https://github.com/simonsobs/pixell/issues/288
The fundamental issue is that the previous `enmap.queb_rotmat` implementation did not respect symmetries required by the DFT of a real map. This induced E<->B mixing at the Nyquist frequency, where these symmetries were being violated by the sine term of the rotmat.  This fix respects the symmetries, and also is consistent for all possible variations of the signs of `cdeltx` and `cdelty` and well as even/odd map shapes in x and y. I added a new test to catch this.
Handling the possibilities of non-standard `cdelt` was important to pass `test_b_sign` in the existing tests -- basically, in the case that a user flips their map in between performing `map2harm` and `harm2map` operations. I generalized this test for all possible …

fixed queb_rotmat, handles all cdelt cases, made tests more general

---

pixell/tilemap.py

This just adds the extra argument in the enmap write_map but for the tilemap write_map. The idea is to have all mapmakers in sotodlib to write the BUNIT keywords in the maps, at the request of @JBorrow and @axf295.

Adding the extra argument for the tilemap write_map function

---

pixell/enplot.py

`IPython.core.display` was deprecated. Replace it with `IPython.display`.

Fix ploting in with ipython
