python/enmap.py

Renamed fft() to fft_map() and ifft() to ifft_map() as there was a
clash of names with the fft module that is imported.
Replaced isinstance comparisons with basestring for something that
works in python2 and python3.
(sorry, I didn't follow the contributing guidelines)

Renamed fft, ifft in enmap.py and fixed py2 -> py3 bug.

---

pixell/enmap.py

Seems I need to change this routine lik so, in order for it to work.  This is (I think) with the 'official' ACT flipper at https://github.com/ACTCollaboration/flipper
Alex

Toflipper tweak

---

CONTRIBUTING.rst

Contributing: elaborate on versioneer and bumpversion.

---

pixell/enmap.py

More generally it will default to sensible behavior for any HDU thing
returned by astropy that does not have .section.
Addresses #96 .  Not sure if it breaks something else.

enmap.read_fits can read CompImageHDU

---

.travis.yml

... by removing unnecessary updates. This should fix the timeout issues. Will merge once tests pass.

Speed up OSX travis

---

pixell/curvedsky.py
pixell/fft.py
pixell/uharm.py
pixell/utils.py

Some more constants. Added utils.inverse_order. Direct access to quadrature weights in curvedsky and uharm. Bugfix in harm2profile_flat_2d, which was centered wrong. space vs tabs in some lines in fft. Make the minfo-building functions in curvedsky accept shape,wcs instead of a full map.

Import from development branch. Relatively minor stuff.

---

pixell/analysis.py

This is meant for analysis of maps, such as matched filtering, object detection, component separation etc. Currently only has matched filtering.

Added pixell.analysis

---

pixell/bunch.py
pixell/fft.py

The main change here is fft.dct and fft.idct, which add support for discrete cosine transforms (and also discrete sine transforms, but those are much less common, so I still used dct in the name). These work like fft.fft, but rely on the real-to-real transform support in very recent versions of pyfftw. They won't work on older versions (including 1.12.0), but this shouldn't affect existing code, just new code that tries to use these functions.
The DCT has some nice properties. Its output is real if the input is real, and has the same data type as the input too. It is also much less vulnerable to implied discontinuities at the end of the array than the standard fft. It is commonly used in image and video compression.

Add fft.dct, fft.idct and let bunch.read specify an hdf group to read from

---

.github/workflows/build.yml
README.rst
setup.py

Returns testing across Python versions.
Uses CodeCov to display test coverage.

Tests and coverage

---

.github/workflows/build.yml
pixell/enplot.py

Fix argparse new syntax

---

.github/workflows/build.yml
README.rst
setup.py

h/t @mhasself for this solution
This fixes #181 
~This reduces minimum Python version to 3.6, and minimum numpy to 1.16.~

Numpy binary incompatibility fix

---

cython/srcsim.pyx
cython/srcsim_core.c
cython/srcsim_core.h
cython/srcsim_wrap.pxd
pixell/cgrid.py
pixell/enmap.py
pixell/enplot.py
pixell/pointsrcs.py
pixell/utils.py

* FIxed bug in sim_objects that would trigger for multi-component maps (e.g. TQU). The bug would lead to the T-map ending up with the U objects in it, while the rest would be empty.
* Added fast radial binning in pointsrcs.radial_bin
* Added control of line width in enplot
* Fixed bounds issue in tsz_tform

Import from dev repo

---

cython/srcsim_core.c
pixell/pointsrcs.py

Handle non-monotonic profiles with arbitrary sign in sim_objects.

Prepare pull

---

cython/distances.pyx

`np.bool` is deprecated for `numpy >= 1.20`. Using `bool` instead should be enough to solve the issue

Remove deprecated `np.bool` in `distances.pyx`

---

pixell/curvedsky.py
pixell/tests/test_pixell.py
setup.cfg

And add unit test to ensure map2alm_healpix keeps working

Fix map2alm_healpix shape bug

---

pixell/curvedsky.py

Conditional import of cmisc to fix readthedocs

---

README.rst

Changes the incorrect information on DUCC0_NUM_THREADS to be more helpful.

Update information on thread numbers

---

setup.py

Clean up after ourselves after compilation checks.

Clean up after compilation checks

---

setup.py

This patch remove logic that auto install cython for the users. I think it is a bit intrusive to the users and the users should be informed to change their environment manually if needed.

remove auto-install for the users

---

.github/workflows/build.yml
setup.cfg

Revert to macos-12

---

.github/workflows/build.yml

Bump CIBuildWheel to target 3.13 Deployment
